// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// matrixCall
void matrixCall(arma::mat A, Function x);
RcppExport SEXP _rcpp101_matrixCall(SEXP ASEXP, SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type A(ASEXP);
    Rcpp::traits::input_parameter< Function >::type x(xSEXP);
    matrixCall(A, x);
    return R_NilValue;
END_RCPP
}
// matrixCall2
void matrixCall2(arma::mat& A, Function x);
RcppExport SEXP _rcpp101_matrixCall2(SEXP ASEXP, SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type A(ASEXP);
    Rcpp::traits::input_parameter< Function >::type x(xSEXP);
    matrixCall2(A, x);
    return R_NilValue;
END_RCPP
}
// matrixCall3
void matrixCall3(NumericMatrix A, Function x);
RcppExport SEXP _rcpp101_matrixCall3(SEXP ASEXP, SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type A(ASEXP);
    Rcpp::traits::input_parameter< Function >::type x(xSEXP);
    matrixCall3(A, x);
    return R_NilValue;
END_RCPP
}
// matrixCall4
void matrixCall4(NumericMatrix& A, Function x);
RcppExport SEXP _rcpp101_matrixCall4(SEXP ASEXP, SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix& >::type A(ASEXP);
    Rcpp::traits::input_parameter< Function >::type x(xSEXP);
    matrixCall4(A, x);
    return R_NilValue;
END_RCPP
}
// accessRmatrix
void accessRmatrix(arma::uword i, arma::uword j, Function x);
RcppExport SEXP _rcpp101_accessRmatrix(SEXP iSEXP, SEXP jSEXP, SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::uword >::type i(iSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type j(jSEXP);
    Rcpp::traits::input_parameter< Function >::type x(xSEXP);
    accessRmatrix(i, j, x);
    return R_NilValue;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_rcpp101_matrixCall", (DL_FUNC) &_rcpp101_matrixCall, 2},
    {"_rcpp101_matrixCall2", (DL_FUNC) &_rcpp101_matrixCall2, 2},
    {"_rcpp101_matrixCall3", (DL_FUNC) &_rcpp101_matrixCall3, 2},
    {"_rcpp101_matrixCall4", (DL_FUNC) &_rcpp101_matrixCall4, 2},
    {"_rcpp101_accessRmatrix", (DL_FUNC) &_rcpp101_accessRmatrix, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_rcpp101(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
