# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

matrixCall <- function(A, x) {
    invisible(.Call(`_rcpp101_matrixCall`, A, x))
}

matrixCall2 <- function(A, x) {
    invisible(.Call(`_rcpp101_matrixCall2`, A, x))
}

matrixCall3 <- function(A, x) {
    invisible(.Call(`_rcpp101_matrixCall3`, A, x))
}

matrixCall4 <- function(A, x) {
    invisible(.Call(`_rcpp101_matrixCall4`, A, x))
}

accessRmatrix <- function(i, j, x) {
    invisible(.Call(`_rcpp101_accessRmatrix`, i, j, x))
}

