# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

matrixCall <- function(A, x) {
    invisible(.Call(`_rcpp101_matrixCall`, A, x))
}

matrixCall2 <- function(A, x) {
    invisible(.Call(`_rcpp101_matrixCall2`, A, x))
}

matrixCall3 <- function(A, x) {
    invisible(.Call(`_rcpp101_matrixCall3`, A, x))
}

matrixCall4 <- function(A, x) {
    invisible(.Call(`_rcpp101_matrixCall4`, A, x))
}

accessRmatrix <- function(i, j, x) {
    invisible(.Call(`_rcpp101_accessRmatrix`, i, j, x))
}

Modmatrix <- function(A, i, j, s) {
    invisible(.Call(`_rcpp101_Modmatrix`, A, i, j, s))
}

equalTest <- function(i, s) {
    invisible(.Call(`_rcpp101_equalTest`, i, s))
}

is_na_arma <- function(A, i, j) {
    .Call(`_rcpp101_is_na_arma`, A, i, j)
}

sub_mat <- function(A, i1, i2, j1, j2) {
    .Call(`_rcpp101_sub_mat`, A, i1, i2, j1, j2)
}

mod_mat <- function(A, i, j, x) {
    .Call(`_rcpp101_mod_mat`, A, i, j, x)
}

return_mat <- function(A) {
    .Call(`_rcpp101_return_mat`, A)
}

mod_mat2 <- function(i, j, x) {
    invisible(.Call(`_rcpp101_mod_mat2`, i, j, x))
}

